services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    ports:
      - "8080"
    volumes:
      - app:/app
      - ./images:/app/images
    depends_on:
      - db
    environment:
      - APP_ENV=DEV

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  app:
  postgresql-data:
  
      
    
