service:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"
    volumes:
      - "app:/app"
      - "./images:/app/images"
    depends_on:
      - db
    environments:
      - APP_ENV=DEV

  db:
    image: postgres:15-alpine
    environments:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data":ro

volumes:
  app-python:
  postgresql-data:
  
      
    
